version: '3.4' #Example http://www.andreavallotti.tech/en/2017/10/using-ef-cores-migration-with-docker-and-mysql/

services:
  
  #mysql:
  #  image: mysql:5.7.18
  #  container_name: flowscript-mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: "p4ssw0r#"
  #    MYSQL_DATABASE: "flowscript"
  #  volumes:
  #    - ./mysql-data:/var/lib/mysql
  #  restart: always
  #  networks:
  #    - nat

  flowscript:
    image: ${DOCKER_REGISTRY-}flowscript
    build:
      context: .
      dockerfile: src\FlowScript\Dockerfile
    #depends_on:
    #  - mysql
    #networks:
    #  - nat

  #volumes:
    #mysql-data:
  
  #network_mode: "bridge"

  #networks:
    #nat:
      #driver: bridge